### ISSUE TITLE
Integer overflow when getting file size larger than 4gb

### ISSUE THREAD

**Issue by mackermans** [eneiluj/integration_onedrive#15]
I have a OneDrive folder which includes a lot of large files (mainly GoPro and drone footage), and when trying to get the download size for one of those files, the following error occurred:

Error: `Return value of OCA\\Onedrive\\Service\\OnedriveStorageAPIService::getFile() must be of the type int or null, float returned`
File: `/var/www/nextcloud/apps/integration_onedrive/lib/Service/OnedriveStorageAPIService.php`

As far as I understand, when the `stat()` PHP method encounters a filesize larger than 4gb (larger than 2^32 bytes), it returns a float.

I think I got around this by changing the return type hint on `getFile()` to be `?float`, and casting in the return by doing `return (float) $stat['size'] ?? 0;`. Though I'm not sure if this would break something else... it's still pretty early in the import process so we'll see.

**Comment by eneiluj** [comment]
Hi,

Thanks a lot for the bug report and the solution suggestion. Returning a float in `getFile()` won't break anything but I think this requires a little bit more changes. It would be cleaner if the `imported_size` config value would be loaded as a float too and then passed (as `$alreadyImportedSize`) as a float parameter in `importFiles()` and `downloadDir()`.

Would you be ready to make a PR for that? If not I'll do it soon.

Thanks again!

**Comment by eneiluj** [comment]
It's done in v0.0.12 which was just released. Could you confirm it now works?

**Comment by mackermans** [comment]
Hi @eneiluj, thanks for fixing the issue and apologies for not getting back earlier! It works great 💯

**Comment by eneiluj** [comment]
Don't apologize, thanks a lot for your feedback!
