### ISSUE TITLE
import of .htaccess files causes "OCP\Files\ForbiddenException: Invalid path"

### ISSUE THREAD

**Issue by ninahubc** [eneiluj/integration_onedrive#16]
If the source Ondrive repository contains any .htaccess file backups, the import process throws a "OCP\Files\ForbiddenException: Invalid path" Error/Exception (found in Error log)

My source of these .htaccess files are simply from directory backups of desktop or mirrored-from-server projects. 

SORT TERM SOLUTION: I manually found all instances of .htaccess and removed the dot for the OneDrive import process.

Don't know if you were aware or wanted to incorporate a better/automated solution/warning/interface message.

**Comment by eneiluj** [comment]
Fixed in v0.0.11 which is out. Thanks for the bug report!
