### ISSUE TITLE
Request: Make the 'Importing...' log message 'Info', not 'Error'?

### ISSUE THREAD

**Issue by ninahubc** [eneiluj/integration_onedrive#17]
Can you make the periodic log message likethe one below an 'Info' message, not an error message?

[integration_onedrive] **Error:** Importing onedrive files for USERNAME  at 2021-02-22T02:15:02+00:00

(Don't know if that is possible due to other constraints).

GREAT PRODUCT, THANK YOU!

**Comment by eneiluj** [comment]
Yep, done and available in v0.0.11.
