### ISSUE TITLE
Ortic/ColorConverter not found when importing calendars

### ISSUE THREAD

**Issue by woutervanoorschot** [eneiluj/integration_onedrive#20]
When importing the calender into nextcloud a http 500 error comes up. In the logging it shows an error that class 'ColorConverter' is not found.

I'm running nextcloud 21 on docker on Debian buster. Is this something with my install, or something wrong with the integration?

```
Exception: Class 'Ortic\ColorConverter\Color' not found

/var/www/html/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch(OCA\Onedrive ... "}, "importCalendar")
/var/www/html/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main("OCA\\Onedri ... r", "importCalendar", OC\AppFramew ... {}, { _route: "i ... "})
/var/www/html/lib/base.php - line 993:
OC\Route\Router->match("/apps/integ ... r")
/var/www/html/index.php - line 37:
OC::handleRequest()

Caused by Error: Class 'Ortic\ColorConverter\Color' not found

/var/www/html/custom_apps/integration_onedrive/lib/Service/OnedriveCalendarAPIService.php - line 101:
OCA\Onedrive\Service\OnedriveColorService->getClosestCssColor("#f495bf")
/var/www/html/custom_apps/integration_onedrive/lib/Service/OnedriveCalendarAPIService.php - line 130:
OCA\Onedrive\Service\OnedriveCalendarAPIService->getCategories("EwCYA8l6BAA ... =", "wouter")
/var/www/html/custom_apps/integration_onedrive/lib/Controller/OnedriveAPIController.php - line 157:
OCA\Onedrive\Service\OnedriveCalendarAPIService->importCalendar("EwCYA8l6BAA ... =", "wouter", "AQMkADAwATM ... =", "Agenda", "#0042c7")
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 218:
OCA\Onedrive\Controller\OnedriveAPIController->importCalendar("AQMkADAwATM ... =", "Agenda", "#0042c7")
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 127:
OC\AppFramework\Http\Dispatcher->executeController(OCA\Onedrive ... "}, "importCalendar")
/var/www/html/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch(OCA\Onedrive ... "}, "importCalendar")
/var/www/html/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main("OCA\\Onedri ... r", "importCalendar", OC\AppFramew ... {}, { _route: "i ... "})
/var/www/html/lib/base.php - line 993:
OC\Route\Router->match("/apps/integ ... r")
/var/www/html/index.php - line 37:
OC::handleRequest()
```

**Comment by eneiluj** [comment]
Hi,

* How did you install the app? In the app settings in the web UI?
* Which version of the app are you using?
* Do you have access to the filesystem where Nextcloud apps are stored? If yes, could you check that `apps/integration_onedrive/vendor/ortic/color-converter/src/Color.php` exists.

My guess is that there is something wrong in your context when loading the composer autoload file. Let's find out.

**Comment by eneiluj** [comment]
I found the problem. The makefile excludes stuff that should be included in the app build archive. I'll fix that and publish another release.

Thanks for the bug report!

**Comment by eneiluj** [comment]
The fixed app has been released for NC 20 and 21 (v1.0.4) and NC 22 (v1.1.0). You should be able to upgrade soon. Could you confirm it works for you with v1.0.4?

**Comment by woutervanoorschot** [comment]
Hi,

I installed it throught the web UI, currently version 1.0.1. Once it is available I'll update if it works.
Thanks for the quick reply!


(I also have some issues with the file sync stuck, but I'll first investigate that myself before opening another issue).

**Comment by woutervanoorschot** [comment]
Sorry for the late reply, the fix works, calendars are imported correctly!
Thanks for this plugin
