### ISSUE TITLE
Only first 200 files imported from OneDrive/Pictures/Camera imports

### ISSUE THREAD

**Issue by shr3k** [eneiluj/integration_onedrive#3]
Hi, this plugin imports only first 200 files from large folders like Camera imports. When you want to import rest, one must delete first 200 from OneDrive.

**Comment by eneiluj** [comment]
Hi, thanks for the bug report.

Are you sure the import process had finished and the migration settings page was saying so?

Files are not imported all at once, it is done by successive background jobs of 500 MB max download each. It is possible the OneDrive API has some limitations and can't return more than 200 files per directory...but it's not mentioned in the documentation.

I'll try to reproduce the problem. To be continued.

**Comment by shr3k** [comment]
Yes, import was succesfully finished, only this one folder with more than 200 files get synced only up to first 200. As I wrote, I can delete first 200 files from Onedrive and with next import it imports second batch and so far so on.

**Comment by eneiluj** [comment]
Very weird. If the files are not there anymore, it should import the same ones, I mean in the same order so you should see the same ones appear.

**Comment by eneiluj** [comment]
v0.0.4 fixes this issue. I didn't know the API could return paginated results. It is actually buried deep in their horrible documentation and weirdly implemented :grin:.

I'm interested to know if everything runs fine on your side too.

**Comment by shr3k** [comment]
Generated 1000 files with random content, 757 MB, synced with OneDrive, imported into Nextcloud, all OK.

**Comment by eneiluj** [comment]
Yay! Thanks for the feedback.
