### ISSUE TITLE
Direct Integration of OneDrive as External Store

### ISSUE THREAD

**Issue by delarius** [eneiluj/integration_onedrive#5]
Hey,

it would be really great, if you could also integrate OneDrive as External Storage for nextcloud.
Some other plugin is already here:
https://github.com/hevelius/files_external_onedrive
But it is not supported anymore .. 
Would be great if you could pickup the ball and make an integration for NC20+

Thanks a lot !!

**Comment by Chevrah** [comment]
Came here to ask for the same. 

I'd love to have onedrive mounted to NC as external storage!

**Comment by eneiluj** [comment]
This is actually possible with latest release of files_external_onedrive
