### ISSUE TITLE
Only import or also sync?

### ISSUE THREAD

**Issue by Weasy666** [eneiluj/integration_onedrive#7]
Hey! First thanks a lot for working on a OneDrive integration.

I would like to know, if this is only for importing OneDrive data for once, or if it also keeps both (Nextcloud and OneDrive) in sync.

**Comment by eneiluj** [comment]
Hey! Thanks for your enthusiasm.

This app imports the data and does not sync it. The goal is to migrate the data from OneDrive to Nextcloud.

**Comment by Weasy666** [comment]
Thanks for answering. That is a shame. A Nextcloud Plugin with two way sync would be really really nice.
