### ISSUE TITLE
Can't import because of faulty remaining space value

### ISSUE THREAD

**Issue by wobfan** [eneiluj/integration_onedrive#8]
My server reports faulty monitoring values, e.g. the remaining space one. It always says '-2 Bytes'

I temporarily worked around by editing `enoughSpaceForOnedrive()` in `nextcloud / apps / integration_onedrive / js / integration_onedrive-personalSettings.js`, so that it does `return 1` without any if condition. Then I was able to start the import in my settings.

Maybe you could add a button to start the import although the server reports too low remaining space, or do a sanity check on the reported value?

**Comment by eneiluj** [comment]
Thanks for the bug report. It was already fixed but not released yet. v0.0.5 includes the fix. Could you confirm it works fine?

**Comment by wobfan** [comment]
Hi! thanks for your immediate response, and indeed yes, the update solved the issue! Thanks!
